Simplify type parameters for schedule_common()
mmtk/mmtk-core pull request #487
Opened 2021-10-28 23:40 UTC by qinsoon

This PR
* adds a new trait `GCWorkContext` which provides a few associated types used for work packets. Each plan provides an implementation of `GCWorkContext`.
* moves `schedule_common` from `CommonPlan` to `GCWorkScheduler`.
* fixes tutorial code for the changes in https://github.com/mmtk/mmtk-core/pull/471.

2021-11-02 23:45 UTC, qinsoon commented on src/plan/global.rs
>          constraints: &'static PlanConstraints,
Done.

2021-11-02 23:47 UTC, qinsoon commented on src/plan/global.rs
>          scheduler: &GCWorkScheduler<VM>,
Good point. I have moved the method to `GCWorkScheduler`. I didn't want to make it the default implementation for the `Plan` trait, as the default implementation cannot be reused if a plan decide to override it.

2021-11-05 06:19 UTC, wks requested changes
There are a few comments that need updating.

2021-11-05 06:19 UTC, wks commented on docs/tutorial/src/mygc/ss/collection.md
> +Though you can add those work packets by yourself, `CommonPlan` provides a
It is now `Scheduler.schedule_common_work`.  There are several other places mentioning `schedule_common` in this file.

2021-11-05 06:19 UTC, wks commented on src/scheduler/work.rs
> +/// create GC work packets for a certain plan. For example, `CommonPlan.schedule_common()`
It is now `Scheduler.schedule_common_work`.

2021-11-08 23:38 UTC, qinsoon commented
I have addressed the reviews. @wks

2021-11-12 03:57 UTC, wks approved these changes
LGTM

2021-11-15 10:14 UTC, merged