Allow bindings to handle unknown objects in trace_object()
mmtk/mmtk-core pull request #593
Opened 2022-05-16 00:25 UTC by qinsoon

2022-06-23 08:10 UTC, wks requested changes
The logic is OK.

There is only a small problem related to the naming of used/unused parameters.

2022-06-23 08:10 UTC, wks commented on src/policy/space.rs
>              _object,
This `_object` has the same problem.  Although it is not related to the bindings, it is nice to fix it, too.

2022-06-24 01:54 UTC, qinsoon commented
I have removed the underscore prefix for those variables.

2022-06-24 02:48 UTC, wks approved these changes
LGTM

2022-06-24 06:37 UTC, merged