Add nonmoving space and allocation semantic
mmtk/mmtk-core pull request #678
Opened 2022-10-07 04:05 UTC by qinsoon

2022-10-09 23:45 UTC, qinsoon commented
binding-refs
JIKESRVM_BINDING_REPO=qinsoon/mmtk-jikesrvm
JIKESRVM_BINDING_REF=non-moving-support

2022-10-10 06:40 UTC, qinsoon commented on src/memory_manager.rs
> +    }
Yeah. It is intended. I think this would be useful when we try to print the allocator config in the future.

2022-10-10 07:06 UTC, wks requested changes
Mostly OK, with some minor errors.

2022-10-10 07:10 UTC, qinsoon commented on src/plan/global.rs
> +    /// reclaim the objects even through they are dead.
Done

2022-10-10 07:10 UTC, qinsoon commented on src/plan/global.rs
> +    /// Non moving objects will not moved by GC.
Done

2022-10-10 07:27 UTC, wks approved these changes
LGTM

2022-10-10 21:11 UTC, merged